apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-auth
    namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:/BoSQzWBGOOlW0gzPJPr4vxah0ZQ2dos+t+CRYOQRto3Wy9EN6N8CDZNc0ukzk1gz/ekV3k4KFosLK7Yb3yn7N3CTsXUdYmHkZosTI+5unudQnpOdZNzEPuG8oPSeOxM4C1Bs7tNwgTBlPMOunS88mOGkLeKnEes0XDdoR4684K3uffEpX7f7dd/8j7XsHtxQhVsw4vSQqPomoDAqb79wOCWhhPZF4EKGw+p/lg9RfRId/flfY/FwsWtCzltwGU/WvOlG31fSfPTVoE+GWjqI5YKYLo5SJaTRlwW2vKdmM8eRa4oFcigl7md9oii/ZRoGnff05m7MvDh,iv:Sg4DoDJaDHvcsOBivQiOtwiu1Yh0JgnPCY3qkzpafig=,tag:s9MaEpMLCLII7WIxgXc5XQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscVZ1Nk1iSlhjT3NwM2dM
            NG4va2RXbWM4dWRncS9HU25MVTcraEphTEE4Ck5GeDNqN05FYVBHRW5DMkJ6ejVY
            RkJSVzJxWko1WGdla1U5a05YS2Fmc2MKLS0tIDdyMEhIeGZaNzB4akJDYVdyRVJG
            UlZHaWlZby9EUTJYYWF2U0xjWnNNWUkK9B/NtF2w+Fc+ARnWnsC/UBf+efjDvtC5
            61ObFxgVpetlh6huMMf+LtiFXg3pu6mULz0oiUqxIKedD0s+nya8LQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10548c2w827sd73a36l4zn8n2m7lsfgyssz6y0d86mzg6xw5s05kqxjnuhe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T21:12:32Z"
    mac: ENC[AES256_GCM,data:SVQHbu2P+NuCTukwHgtfKOQeM55w0FQs8lzWuLd4TW351QCnl72mDY7z+Zh2GS0PQZD0LU3+EsvRxKC2veI0q6Z7GjvQf13qYcBiYV1ZcqPK4+jaG7zQFvavJvhLuasNaKiI6cp1xtNcriBYUl4UjAC0+sEN4qfLZfih7GzkyAc=,iv:3iXhFgwnIU40c+41T4Nj6KiiPiNSdTbXAIuMLLCGK3c=,tag:sllsfhofxO9v7NwdxMXY0A==,type:str]
    version: 3.13.2
