apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-auth
    namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:xHvwlLZpC7pEB8kUoL7V64y49F4N0jdBbWYOiZy9CV+sR9iHUH6KmwVbTReprwbVIgnnZzviZGrnARKH+HRk0jnWDFm6JAL79pj7DZdKMJHL6ejSWTVFWSxsTgypNAMafa6cXs+X67o/XAgNvFzwnYlhAFutVR8UQG/dXMwDFbwF5PStCcozZx+vIHm7VCpo3gFXSzofZN8QkdXMkIaoiI6qAvlu/B0UUzR/arEeN4Uwi03JfgIxlD2KRt1RXrfx53DJAe8P6LoPqeiMGHMKWUE97B9JrU9i3u1c2MdZxNen4y40/Ki47euQnC7mldZXABA4fk0Mov/W,iv:bVpD5qqtJ5dZ7q1dpJnRnoIFtuVzeZPi1C4cYqNbajs=,tag:NG+FhKMcv5d5e+umS1wT2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQjBOb3U3UHhVcldYUHZh
            d0x0T1h6TWhQZHovWG8yU1VFSHFncER3NmdRCmx5V2Y0cUNuQk1VK3hZekhBNzRF
            dk9pcGE0ZWlZeWFTUXpjdG90bmRLbE0KLS0tIEdJNlZIZUFGUGR4U1lYMWlNbUZt
            NFlqSEZpSGQ0eTUzSnF1ZGpNcHlhS28KA7Th9Bdkv2PXCdX/vS5IQJjAm6mSp14/
            fZPxzzEQ9lRHCCQIGiwK/WqqyZJuzyuRy2a/Cb3ozxY7W7lVWSSDRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10548c2w827sd73a36l4zn8n2m7lsfgyssz6y0d86mzg6xw5s05kqxjnuhe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T20:07:28Z"
    mac: ENC[AES256_GCM,data:bFvmYwmPm815QIScX9FlUsiEvnd6KV72LB40D/KTce7S0XoF11H7PtW5tmTfjiSru51ZeNun7hOmRq/rc2/dWPm1Rf0HJveauw7qTqvxEl/qG/AIKuexRwOP6y+18VhaaCtgTJs8mJVJ9IE06pvo7wgbWVFEhMnKUiA2v/vSrBo=,iv:LoN5g8Qv0Nk66hX6ogaKwN496LTiLTxS4O1dcOtOGYA=,tag:7BO6noTEb4fAs6lrIOnPHg==,type:str]
    version: 3.13.2
