apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-auth
    namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:gRQhVe0An++E1qTWpvLvWZqVqsislDkiyfKEWMkADBOikFwgLCHOk2DHTp+fJC+bTk1QtbOVOCgOnD2bGPJFPGkGsJ0tRivV4ctGn73iI3bi3Uc4lqG4pBhbsTmd9uQJ/YYuAgJFS+CPw5leYiKb7eyuVWz3aCGdSg4QsNXpip7pYEAI9mdToWQZPK8I8Hvs4Y+4cY4YdAE7dWsecAliQiIQwsfIvXZrTSfVcycL3Iq5brbem1IyyaKDjtnOyRvkCbH7edzBfH5/vrD7wHAsXbdulvcXMEeekhQBPEhkwC509eZgth0DwsYNe619rFq3c7kfwhW6Jycj,iv:0ctzm5oL38d04NQ07HDhgbNESrFnSQK9c2wNZOeV5F0=,tag:xJCAbZIvE8yrdv6gLTyMoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRVYvMUJ1dUczcmZFeTNL
            eFBYMkpyT1NOVXdTSmlCck5MKzFIM0pCYm04CktyczRHSDZvSHY4WFV3T2RDenNv
            SFZwR1RidGUxV3h4byt5c1phV09OQWsKLS0tIGdxRG1DTDQxcENjVDZ1WTJTNHRM
            SExuWExLb25FU1ZZRTZvNWI3a2RhU3cKGpAxkzU1Vvw2uMhAJXx/TEg1BC85kmJK
            I5NDGSXIFztykYVBVVxksGlpdQTBDrqZ2QpYfh9EUfsrIdk1RD7poQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10548c2w827sd73a36l4zn8n2m7lsfgyssz6y0d86mzg6xw5s05kqxjnuhe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T20:39:42Z"
    mac: ENC[AES256_GCM,data:FQeNfLV4PG9ze/ENwoEY3aAd1R4cX73BQe25DmuV/GSjRg8bTE6X990kEFMW/qTUtjWWfU0mC1PWYGiJk0qVsU6w9bs+5fLG/72QSW87FuSDfX73MMpCl2YRSuPLDggXYRCrVPwaiE2xyALaKhtqwGCud67OEOlTAllgvtRNpjA=,iv:kVFlrF6sUr2hx3XVkfzkqK1k1kSHYqwPa3m+AJhkZMw=,tag:Wbg1RhlxHsdJ5vnsxdcK/A==,type:str]
    version: 3.13.2
