apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-auth
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:UyIXO6sFer/q703fSmXZ0RHN6xOYqZAWwtrYib2Iaop/89o4xI9jwFhUxqUtzyDHoRs9VxkzuB5eHzIN79f/F6qhocu9hrhWP9khNqikaUYli7TEBnSOj3nCfIXisRj5qULmHVH2ApDu8VnwkzyR7ulNT4x96CBzp5Z0TXg5ih+4XhfMvwjaxGKxFJVZ9wRisosN46H3DjJYQI88YxLRPLMEb220uyCw6coBsIXNcLLPRTPQl45hYnB9o0VZKlCVJDL5YJWC+PBJSkZiKJJma2VmpCvGWyLHJmLwm+6DnfUCOs8h1dsKW4AqK8e4QIq2r6NjAFM0UQZg,iv:oIcGSv1vr9rgaw7L89t277s7uUcIs69j1aPxA+cnp3U=,tag:Pejnk7i8vhlV38P0CaH6jA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFN2d1c1FmK3p6bS9JTjBX
            azhtL0F3bFgwaVQ5RW94ekZRd3IvT2JrazBvClBjN3NCQWFjRUprci9rM1RVUEVn
            cFl3RnpzRmo4aE9XMFVrWEsrSjU2blkKLS0tIFFJNHptbHdodHllaFNwYWJGV2JU
            THhlazBuYVI0NENzOEVlUjN3RW4wMTgKmvulfGG3P9FZ6BFrlDzLidMoU925NWGd
            5m3i+8yjbZmnvIw6fYqw9nVMOZYE+nbQkwVIMeMMxXquqxyGWx0Hog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10548c2w827sd73a36l4zn8n2m7lsfgyssz6y0d86mzg6xw5s05kqxjnuhe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T20:07:28Z"
    mac: ENC[AES256_GCM,data:BMs3UKfWQ9oYRE0UwyzVdAo0slPHYwozecKo97TzCc7NVwwHX1cv3etSxCA/tzFJWhs2BvFQ2jR4ns6RWM2aO90y89U2fran57EuAY1YCIiyviPLNajW3Gkh8XklzEzEDinqLeZ2t0naK8l1f+uGaQztR1vUqiraPri7xDt5WbQ=,iv:gIhFGtgcVDMFaviMh3JmJZsB8wqrGV2i3kCqGHXJIQo=,tag:eEfBFpcJ+xby3ADthIr8bQ==,type:str]
    version: 3.13.2
