apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-auth
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:SvaUwwTC5wYm2xT/J8/pPJXD5wKzUZ4q/ABBnwpm/BA8j0NN+Z/xUrgMfb6efEOo4cTLfnBsWhFBsIJkKaGcDtny6vKdzdzH8jccx5M2Sbpye6qYIjtcK8kVqs8PvKxpaWZvN/w+VNR1V0NGHAhsM97Lsf8jSdS8aXaW5aVgQjQeYv2MJfOWvjOR0kgnHX1b2HHktKJvSoLwS+2Sj1uQUFP4Zv4bsr6MnPcdR0VOxOMPqOZgid/4BjWH9DUkAf8s4nco0ZmRqMjb1CS41X8B3ZgHRtclja1hdgJcGNLLGgGFG6ooww==,iv:TAzeZdLsPGpB/haH4/aR+/ZF6g4CwqkvFtnHQOtT9+M=,tag:WK9Bl3hERCfvWkXLFkl31A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQanRmMnJSM2VLbk16ZWM0
            RlpJNW9GcFJXcHNKK2FXTnMzREtReTQzb1UwCm1TeUQ4N3FXNGt2UDJMdTdsZVJL
            SUNKc1hBNFcySUpyaGdkYm9MM0EvWkkKLS0tIE1PSmVXeEllOUNGeGV4TWNWcUw1
            b1I5akZxVWs2UXV0VmZnK0pUdDdrK1EK6arQAGF2DFPqllMJayQdzVApVH85VTWk
            6SKyZN9xbffay81DoD+U/fJw0qHkHvnDtbxjMDpLHrg52kGQQc+2Pg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10548c2w827sd73a36l4zn8n2m7lsfgyssz6y0d86mzg6xw5s05kqxjnuhe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T20:10:07Z"
    mac: ENC[AES256_GCM,data:tV2spDUdqdBgDIGVu2dktwNhFuhm5C2OhUHgLTzOqkcc9gbPP3hVWZ9/srMyMufMAOno2/FnuHjw2DbVXu2ebw8HqyUe3VtPk7iYEIY9jkMVMhZts8jeCeV1FxPZU8Dv2qK3geo2XPC6K3wutCrSYXzbKm58SI5ebFgRUH9X+kg=,iv:bCaWg+rt4aPLvW2Eo6Fa2ZomalinwTK10rMp+jAGeJc=,tag:S8NEIP9QOtLhcdLxiq8dbw==,type:str]
    version: 3.13.2
