apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-auth
    namespace: kommander-flux
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:3sIMng4kj472uh+mxgWAKoJW+cZBb6/V6XezOci/Oj2BnUeg9IGA3fCGRTYQpu3zO+nQH6gxmQ0Vq5tkOkp0x4ClxL15nkyPAmh86Ab4dQ94yukuDmMQE93y/O3q6uUHjqiUdJNORhsTBz78clRiN0Gp3yizMlDn7x3YUquMPZUR8FFU8+GebPeDP9Dl3fb8laJM1D0oq7RX7H/i70AgFx2+XGfVd3kbqVEw8Htu7AS+gVUDf2Sn833HwBagQbVrc3uu90eP3W4TT0mgsZCwCrfm90H/ROUe/H2eHNXsdWBBZ4WHnm641HlQzOzQaSso9w8FWk2WNsBs,iv:6GiSJE9JZv+2zgYwXNQwQfypc6jE3kMPEq7JHL/VOl8=,tag:FPEdMUcGN2PZmtN8Hh+26Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZHdGTFdEK1FOTzBQQzlj
            L29qWTZZRGp6U2xONitPbWlYYUhCejFJb1U4Cmp3cllUc1ZhU0xnTTQ2SnViMVFj
            V3ljbkJSdEZQUkRneURteEpLdjdXcVUKLS0tIE9CQndLK04yaDYwUm9HeXRXdCtm
            RFpJUVZGTjVKRDNSeXFnS0h2bmdKNkkKUKzd9h32YOydGzEa7qpcgsjVzFe5xH9z
            0VgE+QCnBDwT1vjwWWwpuDOEttDtotwlQgjvXyV+0sq7wkC5Gsx1iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10548c2w827sd73a36l4zn8n2m7lsfgyssz6y0d86mzg6xw5s05kqxjnuhe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T21:12:32Z"
    mac: ENC[AES256_GCM,data:SjQI131HrEKY+0TtYdoxZ4h4Kvc3HuDU1OSLUUvRopteNFgHXe8iQ84JDzJw/lhR0rXqtsA/OjFD89AM+GoL+ZrVMtRidcSjDWV4P40QAY/8GUiQHm5OwAIqdp/4r9UqYhmWDkYBM0QTeIts5WupiVVB4tvN5gQkJg8Tu8lQqzo=,iv:t/X58CcSV3pbJ9Gl1hcXNhrP5yC0EF4YaFa96FVnUUg=,tag:vjoGjkvD4NIJPcFV0nc82A==,type:str]
    version: 3.13.2
