apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: demo
  namespace: kommander-flux
spec:
  image: docker.io/fernandoqnutanix/demo
  interval: 1m
  provider: generic
  secretRef:
    name: dockerhub-auth
