apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: demo
  namespace: flux-system
spec:
  image: docker.io/fquinino/demo
  interval: 1m
  provider: generic
  secretRef:
    name: dockerhub-auth
