apiVersion: v1
kind: Namespace
metadata:
  name: demo-federated
  labels:
    kubernetes.io/metadata.name: demo-federated
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedNamespace
metadata:
  name: demo-federated
  namespace: demo-federated
spec:
  placement:
    # Target the workspace-attached downstream cluster(s).
    clusterSelector:
      matchLabels:
        kommander.d2iq.io/workspace-namespace-ref: nkp-workloads01-cqrp5-5gxht
  template:
    metadata:
      name: demo-federated
      namespace: demo-federated
      labels:
        kubernetes.io/metadata.name: demo-federated
